// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqPXu5LX7DMI5pH40irwPmgXG_dz2PbU',
    appId: '1:843312246583:web:9b66c642b21f913c87b4b2',
    messagingSenderId: '843312246583',
    projectId: 'recipeapp-0101',
    authDomain: 'recipeapp-0101.firebaseapp.com',
    storageBucket: 'recipeapp-0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxnoRKwi8YG-ZnzbT7UvcWdCOH5Ag3CTU',
    appId: '1:843312246583:android:bd184b291044700787b4b2',
    messagingSenderId: '843312246583',
    projectId: 'recipeapp-0101',
    storageBucket: 'recipeapp-0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp3ygu2z77NnWaD_UChB_UDA30AZVmJO8',
    appId: '1:843312246583:ios:4d7daf5546a7d54287b4b2',
    messagingSenderId: '843312246583',
    projectId: 'recipeapp-0101',
    storageBucket: 'recipeapp-0101.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp3ygu2z77NnWaD_UChB_UDA30AZVmJO8',
    appId: '1:843312246583:ios:4d7daf5546a7d54287b4b2',
    messagingSenderId: '843312246583',
    projectId: 'recipeapp-0101',
    storageBucket: 'recipeapp-0101.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBqPXu5LX7DMI5pH40irwPmgXG_dz2PbU',
    appId: '1:843312246583:web:59966d6feb9a705587b4b2',
    messagingSenderId: '843312246583',
    projectId: 'recipeapp-0101',
    authDomain: 'recipeapp-0101.firebaseapp.com',
    storageBucket: 'recipeapp-0101.appspot.com',
  );
}
